version: "3"

services:
  influxdb-v2:
    image: influxdb:2.5
    volumes:
      - influxdb-v2:/var/lib/influxdb2:rw
    env_file:
      - ./.env
    ports:
      - 8086:8086
    restart: unless-stopped

  telegraf:
    image: telegraf:1.24.4
    env_file:
      - ./.env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    hostname: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  influxdb-v2:
  grafana-storage:
